### ISSUE TITLE
the name of json property isn't changed when using nested structure.

### ISSUE THREAD

**Issue by fullc0de** [GillianPerard/typescript-json-serializer#53]
I found an issue while I tested a case where a target class has a property whose type is same to its class. `name` property has name alias. So, I expected the last test line must have succeeded. But it failed.

The following is what I expected.
{"isSuperviser":false,"**fullname**":"andrew","superviser":{"isSuperviser":true,"**fullname**":"heath"}}

But, I got the following result.
{"isSuperviser":false,"**fullname**":"andrew","superviser":{"isSuperviser":true,"**name**":"heath"}}

As you can see, the name in the nested object wasn't changed. I'm wondering whether this behavior is intended or not.

You can check whole code below.

```typescript
import { serialize, Serializable, JsonProperty } from 'typescript-json-serializer';

@Serializable()
export class Employee {
    @JsonProperty()
    public isSuperviser: boolean = false;

    @JsonProperty({
        name: "fullname"
    })
    public name: string = "";

    @JsonProperty()
    public superviser: Employee | undefined = undefined;

    public constructor() {}
}

describe("test typescript-json-serializer", () => {

    it("basic functionality", () => {

        let superv = new Employee();
        superv.isSuperviser = true;
        superv.name = "heath";

        let data = serialize(superv);
        expect(data.isSuperviser).toBe(true);
        expect(data.fullname).toBe("heath");
        expect(data.superviser).toBe(undefined);

        let emp = new Employee();
        emp.isSuperviser = false;
        emp.name = "andrew";
        emp.superviser = superv;

        data = serialize(emp);
        console.log(`data = ${JSON.stringify(data)}`);
        expect(data.isSuperviser).toBe(false);
        expect(data.fullname).toBe("andrew");
        expect(data.superviser.isSuperviser).toBe(true);
        expect(data.superviser.fullname).toBe("heath");
    });
});
```

**Comment by fullc0de** [comment]
I met different result with same test code on your library project. I put it as a test in the test directory on the project and then run it and finally got an error like the following.

```
FAIL spec/serialize-nested.spec.ts
  ● test typescript-json-serializer › basic functionality

    TypeError: Cannot read property 'constructor' of undefined

      111 | export function serialize(instance: any, removeUndefined: boolean = true): any {
      112 |     const json: any = {};
    > 113 |     const instanceName: string = instance.constructor.name;
          |                                           ^
      114 |     const baseClassName: string = Reflect.getMetadata(apiMapSerializable, instance.constructor);
      115 |     const apiMapInstanceName: string = `${apiMap}${instanceName}`;
      116 |     const hasMap: boolean = Reflect.hasMetadata(apiMapInstanceName, instance);

      at serialize (src/index.ts:113:43)
      at convertPropertyToData (src/index.ts:171:16)
      at src/index.ts:135:27
          at Array.forEach (<anonymous>)
      at Object.serialize (src/index.ts:131:30)
      at Object.<anonymous> (spec/serialize-nested.spec.ts:33:20)
```
the code was totally same to the one that I attached before.

After that, I found that the problem rises if a class has an object type property and it can be `undefined` or `null` as *optional type*. I fixed it with the following modification of `convertPropertyToData`.

```
```

**Comment by GillianPerard** [comment]
Hi @fullc0de, thank you for your issue, let me check and I'll fix it as soon as possible!

**Comment by GillianPerard** [comment]
Your solution was good, I integrated it and you can use the new version 1.4.3 right now!

**Comment by fullc0de** [comment]
@GillianPerard Thank you for your effort. :-)
