### ISSUE TITLE
Issues with async and await

### ISSUE THREAD

**Issue by webpolis** [GillianPerard/typescript-json-serializer#75]
Hi

I'm getting the following:

```
/home/nico/dev/projects/pidman/node_modules/typescript-json-serializer/index.js:285
            name: key.toString(),
                      ^

TypeError: Cannot read property 'toString' of undefined
    at getJsonPropertyValue (/home/nico/dev/projects/pidman/node_modules/typescript-json-serializer/index.js:285:23)
    at /home/nico/dev/projects/pidman/node_modules/typescript-json-serializer/index.js:103:20

```

This happens just right after I use the `async` and `await` functionality.

E.g. Class' method before async/await. This works with Serializable annotation. No errors here:

```
	kill(signal?: NodeJS.Signals): boolean {
		let ret = true;

		this.processes.forEach((process) => {
			ret = ret && (process.kill(signal));
		});

		return ret;
	}
```

e.g. same class' method after applying `async` and `await`. Error is thrown then:

```
	kill(signal?: NodeJS.Signals): boolean {
		let ret = true;

		this.processes.forEach(async (process) => {
			ret = ret && (await process.kill(signal));
		});

		return ret;
	}
```

I use the serializer library like this:

```
@Serializable()
export class WhateverClass {
```

And I only set one property as serializable on the constructor:

```
constructor(@JsonProperty() private options: GroupOptions)
```

Like said, it works pretty well without async/await... no matter where I use these keywords.

Please advise.

Thanks

**Comment by GillianPerard** [comment]
Hi, thanks to use my lib

Which version do you use?

**Comment by webpolis** [comment]
you're welcome. Thank you for sharing.

2.0.0

**Comment by GillianPerard** [comment]
Could you try with 2.1.0 please.

**Comment by webpolis** [comment]
I've just tried. Same thing.

**Comment by GillianPerard** [comment]
Ok so let me check.

**Comment by GillianPerard** [comment]
Hi, could you provide me a full example (even simpler than yours) that does not work.

I tried this and it works for me:

```ts
@Serializable()
export class GroupOptions {
    @JsonProperty() public options: Array<string>;
}

@Serializable()
export class WhateverClass {
    constructor(@JsonProperty() public groupOptions: GroupOptions) {}
}

const wcData: any = {
    groupOptions: {
        options: ['option1', 'option2']
    }
};

const option = new GroupOptions();
option.options = ['option1', 'option2'];
const wc = new WhateverClass(option);

const promise = new Promise(resolve => {
    setTimeout(() => {
        resolve(deserialize<WhateverClass>(wcData, WhateverClass));
    }, 300);
});

describe('deserialize', () => {
    it('should return true', async () => {
        const result = await promise;
        console.log(result);
        expect(result).toEqual(wc);
    });
});
```

**Comment by webpolis** [comment]
Thanks for testing.

I think the issue arises when you use `async` and `await` inside a **Serialized**'s class method

**Comment by GillianPerard** [comment]
So could you provide me something I can reproduce to be sure to fix?
